version: '3'
services:
  db:
    container_name: mysql
    image: mysql:8.4
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=test
    ports:
      - "3306:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./data/test:/var/lib/mysql
  app:
    container_name: ggb
    image: kimhyensu/ggb:1.0
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/test?useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
    depends_on:
      - db
    healthcheck:
      test: if netstat -ltn | grep -c "8080"; then echo 0; else echo 1; fi
      interval: 10s
      timeout: 5s
      retries: 2