server:
  port: 8080

spring:
  application:
    name: GraduationGoodBye
  sql:
    init:
      mode: never

  # MYSQL
  datasource:
    url: jdbc:mysql://mysql:3306/ggbTest?useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  # REDIS
  data:
    redis:
      host: redis
      port: 6379

    # MONGO
    mongodb:
      uri: mongodb://mongo:27017/test
