server:
  port: 8080

spring:
  # H2
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:log4jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    hikari:
      connection-test-query: SELECT NOW() FROM dual

  # REDIS
  data:
    redis:
      host: localhost
      port: 6379

    # MONGO
    mongodb:
      host: localhost
      port: 27017
      database: local

# MYBATIS 설정
mybatis:
  config-location: classpath:mybatis/sqlmap-config.xml
  mapper-locations: mybatis/map/*.xml
  type-aliases-package: com.ggb.graduationgoodbye.domain