server:
  port: 8081

spring:
  application:
    name: GraduationGoodBye

  # MYSQL
  datasource:
    url: jdbc:mysql://127.0.0.1:13306/main
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:

  # REDIS
  data:
    redis:
      host: redis
      port: 6379

    # MONGO
    mongodb:
      uri: mongodb://mongo:27017/main
