server:
  port: 8080

spring:
  # MYSQL
  datasource:
    url: jdbc:mysql://localhost:3306/ggbTest?useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  # REDIS
  data:
    redis:
      host: localhost
      port: 6379

    # MONGO
    mongodb:
      uri: mongodb://localhost:27017/test

# MYBATIS 설정
mybatis:
  config-location: classpath:mybatis/sqlmap-config.xml
  mapper-locations: mybatis/map/*.xml
  type-aliases-package: com.ggb.graduationgoodbye.domain