# workflow 이름 지정
name: CI/CD

# workflow trigger
on:
  push:
    branches:
      - feature/GGB-09

jobs:
  ci:
    runs-on: ubuntu-latest
    environment: development
    steps:
        # Runner 에 repository 에 저장된 코드 복사
      - name: Checkout code
        uses: actions/checkout@v2

        # SET UP JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

        # APPLICATION-SECRET.YML 등록
      - name: Create application-secret.yml
        run: |
          cat << EOF > src/main/resources/application-secret.yml
          spring:
            servlet:
              multipart:
                enabled: true
                max-file-size: 20MB
                max-request-size: 20MB
            cloud:
              aws:
                credentials:
                  access-key: ${{ secrets.AWS_ACCESS_KEY }}
                  secret-key: ${{ secrets.AWS_SECRET_KEY }}
                region:
                  static: ap-northeast-2
                s3:
                  bucket: ${{ secrets.AWS_S3_BUCKET }}
          EOF

        # BUILD WITH GRADLE
      - name: Build with gradle
        run: ./gradlew clean build

        # DOCKER BUILDX 설정 - Docker 빌드 기능을 확장한 도구
      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v1

        # DOCKERHUB LOGIN
      - name : Login to dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      # DOCKERHUB IMAGE BUILD AND PUSH
      - name: Build and push docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: projectggb/back-end:0.0.1
  cd:
    runs-on: ubuntu-latest
    environment: development
    needs: ci
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy files via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST}}
          username: ${{ secrets.EC2_USERNAME}}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          script: |
            docker pull projectggb/back-end:0.0.1
            docker stop ggb-back || true
            docker rm ggb-back || true
            docker run -d --name ggb-back -p 8081:8080 projectggb/back-end:0.0.1
            docker image prune -af