# workflow 이름 지정
name: CI/CD

# workflow trigger
on:
  push:
    branches:
      - feature/GGB-09

jobs:
  build:
    runs-on: ubuntu-latest
    environment: development
    steps:
        # Runner 에 repository 에 저장된 코드 복사
      - name: Checkout code
        uses: actions/checkout@v2

        # SET UP JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'

        # BUILD WITH GRADLE
      - name: Build with gradle
        run: ./gradlew clean build

        # DOCKER BUILDX 설정 - Docker 빌드 기능을 확장한 도구
      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v1

        # DOCKERHUB LOGIN
      - name : Login to dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      # DOCKERHUB IMAGE BUILD AND PUSH
      - name: Build and push docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: projectggb/back-end:0.0.1